"""Add login column to agents

Revision ID: 10a112e99f63
Revises: 
Create Date: 2026-03-25 10:54:28.099470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a112e99f63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Шаг 1: Добавить колонку как nullable (для существующих записей)
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=100), nullable=True))
    
    # Шаг 2: Заполнить существующие записи (agent_1, agent_2, ...)
    # Для MySQL используем CONCAT
    op.execute("UPDATE agents SET login = CONCAT('agent_', id)")
    
    # Шаг 3: Сделать колонку NOT NULL и добавить уникальный индекс
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('login', existing_type=sa.String(length=100), nullable=False)
        batch_op.create_index(batch_op.f('ix_agents_login'), ['login'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_login'))
        batch_op.drop_column('login')

    # ### end Alembic commands ###
